# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changetime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedatas',
            name='change_time',
            field=models.DateTimeField(verbose_name='Change'),
        ),
    ]
